[functions]
directory = "netlify/functions"
node_bundler = "nft"

[build.environment]
SECRETS_SCAN_OMIT_PATHS = "dist,.netlify"
SECRETS_SCAN_OMIT_KEYS = "GMAIL_USER"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200